//
//  DrawingRouter.swift
//  swift-drawingapp
//
//  Created by USER on 2022/10/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DrawingRoutingLogic { }

protocol DrawingDataPassing {
    var dataStore: DrawingDataStore? { get }
}

class DrawingRouter: NSObject, DrawingRoutingLogic, DrawingDataPassing {
    weak var viewController: DrawingViewController?
    var dataStore: DrawingDataStore?
}
