//
//  DrawingModels.swift
//  swift-drawingapp
//
//  Created by USER on 2022/10/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Drawing {
    
    enum AddSquareEvent {
        struct Request {
            let bounds: CGSize
        }

        struct Response {
            let rect: CGRect
            let color: UIColor
        }
        
        typealias ViewModel = Response
    }
    
    enum DrawEvent {
        struct Request {
            let bounds: CGRect
        }
        
        typealias Response = AddSquareEvent.Response
        typealias ViewModel = AddSquareEvent.ViewModel
    }
}
