//
//  DrawingInteractor.swift
//  swift-drawingapp
//
//  Created by USER on 2022/10/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol DrawingBusinessLogic {
    func addSquare(request: Drawing.AddSquareEvent.Request)
    func addLine(request: Drawing.DrawEvent.Request)
}

protocol DrawingDataStore { }

class DrawingInteractor: DrawingBusinessLogic, DrawingDataStore {
    var presenter: DrawingPresentationLogic?
    var worker: DrawingWorker?

    func addSquare(request: Drawing.AddSquareEvent.Request) {
    }
    
    func addLine(request: Drawing.DrawEvent.Request) {
    }
}
