//
//  DrawingPresenter.swift
//  swift-drawingapp
//
//  Created by USER on 2022/10/19.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrawingPresentationLogic {
    func presentSquare(response: Drawing.AddSquareEvent.Response)
    func presentDraw(response: Drawing.DrawEvent.Response)
}

class DrawingPresenter: DrawingPresentationLogic {
    weak var viewController: DrawingDisplayLogic?

    func presentSquare(response: Drawing.AddSquareEvent.Response) {
        let viewModel = Drawing.AddSquareEvent.ViewModel(rect: response.rect, color: response.color)
        viewController?.disPlayNewSquareView(viewModel: viewModel)
    }
    
    func presentDraw(response: Drawing.DrawEvent.Response) {
        let viewModel = Drawing.DrawEvent.ViewModel(rect: response.rect, color: response.color)
        viewController?.disPlayNewDrawView(viewModel: viewModel)
    }
}
